---
- name: Filter lines from files
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Filter lines containing a specific string
      ansible.builtin.shell: grep -v "{{ exstr }}" "{{ src }}" > "{{ dst }}"
      args:
        executable: /bin/bash
      changed_when: false
#
