- name: Copy directory using rsync
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Copy directory
      ansible.posix.synchronize:
        src: "{{ src }}/"
        dest: "{{ dst }}/"
        recursive: true
#
