---
- name: Copy file
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Copy file
      ansible.builtin.copy:
        src: "{{ src }}"
        dest: "{{ dst }}"
        remote_src: true
        mode: "0644"
#
